### PR TITLE
Little bug fixes

### PR DESCRIPTION
**Pull request by dzervas**
I fixed some small bugs.
Changed hashbang to `#!/usr/bin/env python2` (python3 is waiting around the corner to mess with you)
Moved `__future__` import on the first line (for some reason that's required by python)
`List_Commands` after selecting `ALL` showed wrong commands
Explained that `Make_File`/`Make_Binary` actually sends a file (maybe it should be renamed to Push?)

### CODE REVIEW

**Comment by dzervas** [comment]
I added some more patches.
Ctrl-C on server now closes the sockets
Pressing enter with empty command does nothing (it spit out error about command)
Fixed `Make_File` with non-existing file. Used to break communication (Server was sending filename before checking if the file exists)

**Comment by dzervas** [comment]
Fixed #13!

**Comment by dzervas** [comment]
Fixed #11

**Comment by panagiks** [comment]
Let me start with thanking you for your contribution! 
Now a few notes : 
- Try opening a new pull request for every change (so if a change is to be rejected the rest can still be merged)
- Since the project is using a [styleguide](https://google.github.io/styleguide/pyguide.html) try to follow the guidelines (i.e. not x is None should have been x is not None) also try running your code through [PyLint](https://www.pylint.org/) it'll catch most of the styling errors (and others).
- Try to follow the project's paradigm. I.e. commands from server to client are sent as a string of numbers (0-9) translated server-side through the "CC" dictionary and client-side through the "COMM_DICT" dictionary.
- .gitignore does not need to be on the repository

Now on to the commit itself. All imports should have been above the **attributes** and under the docstring (according to the styleguide), something that totally slept my attention in the last version :s. 

On the client script. address doesn't need to be global. Since reconnect is not run through "COMM_DICT" (in which case for uniformity purposes reconnect could only take sock as an argument) address can be passed when calling the function. About the changes in get_en_data. any handling should be made through the dictionaries (so in this case a new entry -say '00009':'pong'- would be added to COMM_DICT, another to COMM_SWTCH -say 'pong':pong- and a function called "pong" taking sock as its argument). Finally,  if the server exits without disconnecting the client, the later crashes with "global name 'ConnectionRefusedError' is not defined".
screenshot from 2016-06-17 07-19-05

On the server script. The logging methods print output on the command line breaking the program's usage flow (and aesthetics -not that it had any great :p-).
screenshot from 2016-06-17 06-58-04

The idea behind reconnect was great none the less. Keep up the grate work. I will test this pull request more thoroughly as soon as I have some time, merge it and change back anything that has to be changed back.

**Comment by dzervas** [comment]
How the hell can I create a different request?
I mean when I opened the request I just attached "master" so whenever I commit to my repo it's added to the request. What should I do differently?

Oh, I did not notice the styleguide!
And did not think about the CC either :P (I was "in the zone")
About the gitignore, .pyc really gets on my nerves...

As for the address being global, it needs to be global or we have to pass it around every function call.
I tried to work around it but I couldn't
The connectionrefusederror is due to python 2. (Are we writing 2 or 3? or both?)
Well the logging for now is supposed t break the flow (assuming we are in alpha/beta version).
It's just a variable change to log to a file (as discussed in #12 )

BTW: I think the title is kinda misleading :P

**Comment by panagiks** [comment]
Make a branch for each change, make a new request for each branch. 

About .gitignore fell free to use it locally but there is no need for it to be included in the repository.

About the global variables it is supposed to be passed in each function. It provides a more modular approach and ensure that only parts will have to get changed.

About python. The project is currently using python 2.7, as discussed in #9 compatibility with 3+ is a future enhancement.

The project is currently part  of two Distributions' repositories so I wouldn't say it's in alpha/beta it's in production since it's actively being used. So changes made should not break the very functionality. 

I hope I will have some time to review & test the code tomorrow or Sunday.

**Comment by panagiks** [comment]
Hello @dzervas !

I have created a new Branch `Beta` for contributions to go into. So please at your convenience open a new pull request from your `master` branch to the `Beta` branch so I can merge it and do the appropriate changes for your contribution to be included in the main program.

Again thank you very much for your contribution and I hope you can stick around in the project (also sorry for the delay I'm a bit in over my head these days :s )

**Comment by dzervas** [comment]
Oh, cool.

Yes, of course I'll stick around. I'm working on a huge change. I'll rewrite all the code OO. I'm currently designing the whole thing. You'll be able to have plugins that extend the commands (for example UDP flood & file transfer will be plugins)

**Comment by dzervas** [comment]
NOTE: some of the changes on the client have to be applied to min too.

**Comment by panagiks** [comment]
Ok, since you're working on a big rework of the code I'll close this pull request and fix the bugs you reported here so that that main repository contains an actually stable version until you finish.

**Pull request closed without merging**
